server:
  sv_allow_origins: *
  sv_allow_methods: GET, POST, PUT, DELETE
  sv_allow_headers: content-type
  sv_content_type: application/json
database:
  db_host: 127.0.0.1
  db_port: 9001
  db_user: dev
  db_password: 123456
  db_name: isft
states-machine:
  preinscription_on_proc: PRE-PROC
  preinscription: PRE-I
  preinscription_in_list: PRE-LIST
  inscript: INSCR
  annulled: ANLD
  annulled_inscript: ANLD-I